# This dockerfile is meant to help with setup and testing of
# patroni nodes.  It is designed to use kubernetes to support
# multiple nodes

FROM fedora:23

ADD ./pc4patroni/ /scripts/
ADD ./rpm/ /rpm/

RUN /scripts/package_install.sh

EXPOSE 6432

ENTRYPOINT ["/bin/bash", "/scripts/entrypoint.sh"]
